#include "EmbedAsset.hpp"

#include <fstream>
#include <ostream>

#include "Texture.hpp"
#include "Utils/Log.hpp"

namespace ox {
void EmbedAsset::EmbedTexture(const std::string& texFilePath, const std::string& outPath, const std::string& arrayName) {
  uint32_t width, height, bits;
  const auto texture = Texture::load_stb_image(texFilePath, &width, &height, &bits);

  const uint32_t psize = width * height * 4;
  std::ofstream file;
  file.open(outPath);
  file << "// Generated by Oxylus using " << texFilePath << "\n";
  file << "#pragma once" << "\n";
  file << "static constexpr unsigned int " << arrayName << "Width = " << width << ";" << "\n";
  file << "static constexpr unsigned int " << arrayName << "Height = " << height << ";" << "\n";
  file << "static constexpr unsigned char " << arrayName << "[] = {" << "\n";
  size_t j = 1;
  for (size_t i = 0; i < psize; ++i) {
    file << (int)texture[i];
    if (i != psize - 1)
      file << ",";
    if (i == 100 * j) {
      file << "\n";
      j += 1;
    }
  }
  file << "};";

  OX_LOG_INFO("Successfully embedded texture {0} into: {1}", texFilePath, outPath);

  file.close();
  delete texture;
}
}
